Add CI and fix issues
null-domain/bannou pull request #13
Opened 2023-03-18 20:56 UTC by davfsa

2023-03-18 22:36 UTC, davfsa commented on bannou/database/tags.py
> +    created_on: datetime.datetime = ormar.DateTime(nullable=True, server_default=sqlalchemy.func.now())
```suggestion
    created_on: datetime.datetime = ormar.DateTime(nullable=False, server_default=sqlalchemy.func.now())
```

2023-03-19 14:53 UTC, null-domain requested changes
What's the plan for dealing with the failing slotscheck tests?

2023-03-19 14:53 UTC, null-domain commented on alembic.ini
> +file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d_%%(minute).2d_%%(second).2d.%%(rev)s
Any reason we use the revision hash in the filename as opposed to the slug? IMO slug is better to provide an 'at a glance' description of what the revision does without having to open it.

2023-03-19 14:53 UTC, null-domain commented on bannou/settings.py
>              "DSN("
I forgot to change this whenever I made the PR to rename DSN to Service, but the beginning of the repr here should be changed to match.

2023-03-19 14:53 UTC, null-domain commented on config.example.yaml
> +    #   backupCount: 5
Why is it commented out by default?

2023-03-19 14:53 UTC, null-domain commented on dev-requirements.txt
> +alembic[tz]==1.10.2
Alembic would be needed in a production environment, not a development environment, unless you're making bigbrain moves I can't see yet

2023-03-19 14:53 UTC, null-domain commented on scripts/migrations/env.py
> +from sqlalchemy.ext import asyncio as sqlachademy_asyncio
`sqlalchemy` not `sqlachademy`

2023-03-20 17:41 UTC, null-domain commented
Noting the issues you're facing with using ormar (and I'm spotting a few minor faults that, while not huge issues, are still just annoying) - would it be worth ditching ormar in its entirety and just [using SQLAlchemy models directly](https://docs.sqlalchemy.org/en/20/orm/quickstart.html#declare-models)?

Downside of doing so is we lose the cleanliness of ormar models, plus the strong-typing and validation of them (since ormar models are based on Pydantic models underneath), but the upside would be that we could have stronger control over how the models work.

2023-03-26 16:47 UTC, null-domain commented
Merging this for the time being so progress can continue. We can revisit in the future (particularly to sort out the slotscheck issue) and see what else needs to change.

2023-03-26 16:47 UTC, null-domain approved these changes

2023-03-26 16:51 UTC, merged