Murder ORM
null-domain/bannou pull request #27
Opened 2023-04-01 17:27 UTC by HyperGH

harr harr harr

2023-04-02 15:42 UTC, davfsa requested changes
I am personally not loving not using a well established ORM idea, as I feel that it might end up in a lot mistakes down the line by making our own thin orm.

It would be nice if the ORM could be improved a bit more, specially when it comes to db -> object as well as query building

Also, the PR name is misleading, since we are just replacing a orm library with our own

2023-04-02 15:42 UTC, davfsa commented on bannou/database/models/tags.py
> +        query = "SELECT * FROM tags WHERE guild_id = $1 AND tag_name = $2"
Since these are constants, instead of having to keep building them, can we extract them?

2023-04-02 15:42 UTC, davfsa commented on bannou/database/models/tags.py
> +        record = await cls._db.fetchrow(query, hikari.Snowflake(guild), name)
instead of casting to a snowflake, you can use `int`

2023-04-02 15:42 UTC, davfsa commented on bannou/database/models/tags.py
> +            await cls._db.execute(query, hikari.Snowflake(guild), name, hikari.Snowflake(owner), content)
Dito above

2023-04-02 15:42 UTC, davfsa commented on bannou/database/models/tags.py
> +            raise ValueError(f"Tag '{name}' already exists for guild '{hikari.Snowflake(guild)}'.")
```suggestion
            raise ValueError(f"Tag '{name}' already exists for guild '{int(guild)}'.")
```

2023-04-02 15:42 UTC, davfsa commented on bannou/database/models/tags.py
> +        If a tag already exists, overwrite it."""
```suggestion
        """Save the current state of the tag instance to the database.

        If a tag already exists, overwrite it.
        """
```

2023-04-02 15:42 UTC, davfsa commented on bannou/database/models/tags.py
> +        name: `str`
This doesnt follow numpy convetions:
- Space after the name of the parameter
- No `` around the type

https://numpydoc.readthedocs.io/en/latest/format.html#parameters

2023-04-02 15:42 UTC, davfsa commented on bannou/database/models/guilds.py
> +        ON CONFLICT (guild_id) DO NOTHING"""
```suggestion
        query = "INSERT INTO guilds (guild_id) VALUES ($1) ON CONFLICT (guild_id) DO NOTHING"
```

If splitting is necessary, it should be done with a single string

2023-04-02 15:42 UTC, davfsa commented on bannou/database/models/guilds.py
> +        return cls(hikari.Snowflake(guild))
Why so many casts?

2023-04-02 15:42 UTC, davfsa commented on bannou/database/models/guilds.py
> +            raise ValueError(f"Guild '{hikari.Snowflake(guild)}' already exists in database.")
Couldnt we just leave it as a `asyncpg.UniqueViolationError`?

2023-04-02 15:42 UTC, davfsa commented on bannou/database/models/guilds.py
> +    id: hikari.Snowflake = attr.field(on_setattr=attr.setters.frozen)
Shouldnt all database models be frozen?

2023-04-02 15:42 UTC, davfsa commented on bannou/database/models/tags.py
> +    uses: int = 0
For explicity sake, can we make these `attr.field()`?

2023-04-02 15:42 UTC, davfsa commented on bannou/database/models/tags.py
> +@attr.define()
```suggestion
@attr.define(weakref_slot=False)
```
Since we wont be using it and saves on memory

2023-04-02 15:42 UTC, davfsa commented on bannou/database/models/tags.py
> +    async def fetch_all(cls, guild: hikari.SnowflakeishOr[hikari.PartialGuild]) -> list[Tag]:
This should not be typed as returning a list, but rather a sequence, its not something that should be modifiable

2023-04-02 15:42 UTC, davfsa commented on bannou/database/models/tags.py
> +        return [cls.from_record(record) for record in records]
```suggestion
        return tuple(map(cls.from_record, records))
```

2023-04-02 15:42 UTC, davfsa commented on bannou/database/base.py
> +    def from_record(self, record: asyncpg.Record) -> DatabaseModel:
```suggestion
    @abc.abstractmethod
    @classmethod
    def from_record(cls, record: asyncpg.Record) -> DatabaseModel:
```

2023-04-02 15:42 UTC, davfsa commented on bannou/client.py
> +        .set_type_dependency(base.Database, base.Database(bot, settings.BOT_SETTINGS.postgres))
This can be done in another pr, but since the bot settings dont need to be "global state" anymore, can we instantiate them here instead?

2023-04-02 15:42 UTC, davfsa commented on bannou/database/base.py
> +    from bannou.settings import Service
Imports should be of the module, not specific classes

2023-04-02 15:42 UTC, davfsa commented on bannou/database/base.py
> +            raise ValueError("Database pool is not initialized")
```suggestion
            raise RuntimeError("Database pool is not initialized")
```

2023-04-02 15:42 UTC, davfsa commented on bannou/database/base.py
> +            raise hikari.ComponentStateConflictError("Database is already closed")
Why are we raising a hikari error?

2023-04-02 15:42 UTC, davfsa commented on bannou/database/base.py
> +        con: asyncpg.Connection = await self.pool.acquire()  # type: ignore
type ignores should be documented and (if possible) the ignore should be more specific

2023-04-02 15:42 UTC, davfsa commented on bannou/database/base.py
> +        DatabaseModel._app = app
Instead of using a semi-global state here, cant we just have a "metadata" field in the database models and pass db and app around when needed?

2023-04-02 15:49 UTC, null-domain commented on bannou/database/models/guilds.py
> +            raise ValueError(f"Guild '{hikari.Snowflake(guild)}' already exists in database.")
Think my reasoning for this at the time is so we don't have to import any asyncpg exceptions, since ValueError is global it's easier caught. I think Hyper and I mentioned that further down the line we'd be raising custom exceptions instead.

2023-04-02 15:50 UTC, null-domain commented on bannou/database/models/guilds.py
> +    id: hikari.Snowflake = attr.field(on_setattr=attr.setters.frozen)
A guild ID never changes, whereas something like a tag_name could change, so no

2023-04-02 15:55 UTC, null-domain commented on bannou/database/base.py
> +        con: asyncpg.Connection = await self.pool.acquire()  # type: ignore
I'm not familiar with `type: ignore` statements - this is my first project where I've used something like mypy and slotscheck. Any documentation on `type:` statements, and where should *we* document our use of them?

2023-04-02 16:05 UTC, davfsa commented on bannou/database/models/guilds.py
> +            raise ValueError(f"Guild '{hikari.Snowflake(guild)}' already exists in database.")
What i mean is, we shouldnt really need to try and then re-raise an error here. We can just let the `asyncpg.UniqueViolationError` bubble up.

2023-04-02 16:07 UTC, davfsa commented on bannou/database/models/guilds.py
> +    id: hikari.Snowflake = attr.field(on_setattr=attr.setters.frozen)
But then they stop representing data from the database. So do we want models to be a one way mirror into the database or actually editable?

2023-04-02 16:09 UTC, null-domain commented on bannou/database/models/guilds.py
> +    id: hikari.Snowflake = attr.field(on_setattr=attr.setters.frozen)
I did it this way as once a guild object is created, the ID of it should never change. For this same reason I wouldn't be having any method to delete a guild object from the database, only to reset/nullify any columns associated with the guild ID.

2023-04-02 16:09 UTC, davfsa commented on bannou/database/base.py
> +        con: asyncpg.Connection = await self.pool.acquire()  # type: ignore
All mypy errors have an "error-code" to specify which ones should be ignored (https://mypy.readthedocs.io/en/stable/type_inference_and_annotations.html?highlight=ignore#type-ignore-error-codes). We should be making use of that.

2023-04-02 16:12 UTC, davfsa commented on bannou/database/base.py
> +        con: asyncpg.Connection = await self.pool.acquire()  # type: ignore
Additionally, these type ignores tend to be because you are typing con as being `asyncpg.Connection`, when in reality what we are getting is `PoolConnectionProxy`. (https://github.com/MagicStack/asyncpg/blob/master/asyncpg/pool.py#L134)

2023-04-02 16:12 UTC, null-domain commented on bannou/database/models/guilds.py
> +    id: hikari.Snowflake = attr.field(on_setattr=attr.setters.frozen)
IMO any major identifying columns (like, for example, a guild ID) should be frozen and uneditable once saved or when retrieved from the database.

2023-04-02 16:21 UTC, davfsa commented on bannou/database/models/guilds.py
> +    id: hikari.Snowflake = attr.field(on_setattr=attr.setters.frozen)
Yeah, that makes sense to limit, but at a database level, not at a model level. Models (at least the way i see us treating them) will just be a one way mirror to the database, so there is no need to ever edit them from python code, making them basically frozen

2023-04-02 16:26 UTC, null-domain commented on bannou/database/models/guilds.py
> +    id: hikari.Snowflake = attr.field(on_setattr=attr.setters.frozen)
But models would and should be editable as a Python object - take a tag for example, we can fetch it from the database (which creates it as a Py object), edit the name or the content of it (as the object), and then save it back to the database, with one function call - all the SQL is abstracted away underneath in the model itself.

2023-04-02 16:33 UTC, davfsa commented on bannou/database/models/guilds.py
> +        query = "SELECT * FROM guilds WHERE guild_id = $1"
The biggest issue I have with this is the use of `*` that this and many other queries will have.

I would much rather have a properly built query system that fetches/executes and validates data as we need it, not select everything from a database just to check if the guild exists in the database, as this PR just introduces another ORM.

2023-04-02 16:37 UTC, null-domain commented on bannou/database/base.py
> +        con: asyncpg.Connection = await self.pool.acquire()  # type: ignore
If we ever were to write a query ourselves outside of a model, we'd use acquire for that. Hopefully we never need to, but /shrug

2023-04-02 16:38 UTC, null-domain commented on bannou/database/models/guilds.py
> +        query = "SELECT * FROM guilds WHERE guild_id = $1"
Yeah I'll admit this one's on me, I kind of just copy-pasted everything from tags without giving it a second thought. Just wanted to lay out a base with more than one example of a model.

2023-04-02 16:39 UTC, davfsa commented on bannou/database/models/guilds.py
> +        query = "SELECT * FROM guilds WHERE guild_id = $1"
Yeah, what im saying is that maybe the idea needs to be revised and truly move away from ORM with a proper query builder system

2023-04-02 16:48 UTC, null-domain commented on bannou/database/models/guilds.py
> +        query = "SELECT * FROM guilds WHERE guild_id = $1"
I ain't got the skill for allat

2023-04-02 17:06 UTC, null-domain commented on bannou/database/base.py
> +            raise hikari.ComponentStateConflictError("Database is already closed")
@HyperGH this ones all you my guy

2023-04-02 17:14 UTC, null-domain commented on bannou/client.py
> +        .set_type_dependency(base.Database, base.Database(bot, settings.BOT_SETTINGS.postgres))
Yyyyyes but I would do this in another PR like you said - I want to get migrations sorted in this PR and that might require some additional consideration re how settings work

2023-06-03 22:27 UTC, null-domain commented
Closed in favour of #24

2023-06-03 22:27 UTC, closed without merging