Setup ORM with alembic for migrations
null-domain/bannou pull request #9
Opened 2023-03-16 19:51 UTC by null-domain

2023-03-16 22:18 UTC, davfsa requested changes

2023-03-16 22:18 UTC, davfsa commented on bannou/client.py
> +from databases import Database as DatabaseType
As a coding practice, should we keep in-line with hikari and import the modules and then refer to them? I find it nicer to then pinpoint where classes are coming from and being defined

2023-03-16 22:18 UTC, davfsa commented on bannou/database/context.py
> +    metadata = _metadata
```suggestion
class BaseMeta(ModelMeta):
    database = Database(bot_settings.postgres.build_url())
    metadata = sqlalchemy.MetaData()
```

2023-03-16 22:18 UTC, davfsa commented on bannou/database/migrations/env.py
> +    here as well.  By skipping the Engine creation
```suggestion
    here as well. By skipping the Engine creation
```

2023-03-16 22:18 UTC, davfsa commented on bannou/database/migrations/env.py
> +    asyncio.run(run_migrations_online())
If this is going to be a script, wouldnt it be better to keep it outside of the bot source code and into a `scripts` folder?

2023-03-16 22:18 UTC, davfsa commented on bannou/database/models/__init__.py
> +from .tags import Tag
```suggestion
from bannou.database.context import BaseMeta

from bannou.database.models.tags import Tag
```

Relative imports can be really hard to follow and maintain

2023-03-16 22:18 UTC, davfsa commented on bannou/database/models/tags.py
> +from . import BaseMeta
Same here

2023-03-16 22:18 UTC, davfsa commented on pyproject.toml
> +"bannou/database/models/__init__.py" = ["F401"]
Missing new line

2023-03-16 22:18 UTC, davfsa commented on pyproject.toml
> +"bannou/database/migrations/env.py" = ["F401"]
Can we try to document these codes right above with a meaningful description on why they are ignored?

2023-03-16 22:18 UTC, davfsa commented on bannou/__init__.py
> +bot_settings = settings.BotSettings("config.yaml")
Dont like this change at all. This would mean that settings are read off at import time, which should only be happening when needed. Init files should not contain any logic unless strictly necessary. Not only that, this also assumes that the module is being imported from the path that config.yaml is in.

For the single place where this is being "useful", we can just add an init to the class and pass the settings.

2023-03-16 22:18 UTC, davfsa commented on bannou/database/migrations/env.py
> +import bannou.database.context
To differentiate alembic context and bannou context, we can use `as alembic_context` and `as bannou_context` respectively

2023-03-16 23:40 UTC, null-domain commented on bannou/client.py
> +from databases import Database as DatabaseType
Can do

2023-03-16 23:41 UTC, null-domain commented on bannou/database/context.py
> +    metadata = _metadata
I had it like this before but changed it to what it is now - can't actually remember _why_ I did that. Can always change it back if it breaks but I don't think it should, probably was just me being an idiot

2023-03-16 23:42 UTC, null-domain commented on bannou/database/migrations/env.py
> +    asyncio.run(run_migrations_online())
Unfortunately the directory structure of `bannou/database/migrations` is set up and managed by alembic, I'm not sure if we can change the location of this.

2023-03-16 23:42 UTC, null-domain commented on bannou/database/models/__init__.py
> +from .tags import Tag
Gotcha, will keep to this practice

2023-03-16 23:53 UTC, null-domain commented on bannou/__init__.py
> +bot_settings = settings.BotSettings("config.yaml")
Not entirely sure how I would go about doing this 'cleanly'. Will mention it tomorrow

2023-03-16 23:56 UTC, null-domain commented on bannou/database/migrations/env.py
> +    asyncio.run(run_migrations_online())
Actually I think we can. Will play around and see what I can achieve

2023-03-17 12:44 UTC, davfsa commented on bannou/client.py
> +from bannou.database.context import BaseMeta
```suggestion
from bannou import settings
from bannou.database import context
```

2023-03-17 12:44 UTC, davfsa commented on bannou/client.py
> +import databases
Out of curiosity, where does this import come from?

2023-03-17 12:44 UTC, davfsa commented on bannou/database/migrations/env.py
> +from bannou.database import models
If F401 is only for here, cant we just ignore it in-line?

2023-03-17 12:44 UTC, davfsa commented on bannou/database/context.py
> +    database = Database(settings.BotSettings("config.yaml").postgres.build_url())
Ngl, kinda hate this even more.

Instead of having it in the init, what about having settings.py export the loaded class already?

Will most probably make it tricky in the future to test, if we do get around to setting that up, but should be doable. This is loading the config file anyways.

2023-03-17 13:10 UTC, null-domain commented on bannou/client.py
> +from bannou.database.context import BaseMeta
The change on line 8 would affect the parameter name for `build_bot(settings: ...)`.
`from bannou.settings import BotSettings` was how you originally did it in 0778386.

2023-03-17 13:10 UTC, null-domain commented on bannou/client.py
> +import databases
This import is for [encode/databases](https://github.com/encode/databases). The only place we use this import or its classes directly is for connecting and closing connections to the database, and for the BaseMeta class for DB models.

2023-03-18 11:43 UTC, davfsa approved these changes

2023-03-18 11:44 UTC, merged